matrix:
  include:
  - language: objective-c
    osx_image: xcode11.2
    xcode_sdk: iphonesimulator13.2
    xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone X
    env: NODE_VERSION=12.13.0
    branches:
      only:
      - master
    cache: yarn
    install:
    - nvm --version
    - echo $NODE_VERSION
    - sudo launchctl limit maxfiles 2048 unlimited
    - sudo ulimit -n 10000
    - brew tap wix/brew
    - brew install applesimutils
    - brew update
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
    - nvm alias default $NODE_VERSION
    - brew install yarn
    - yarn cache clean
    - yarn install --network-concurrency 1
    - yarn global add react-native-cli
    - yarn global add detox-cli
    - yarn
    - yarn nodeify
    - pod repo update
    - yarn install-pods
    - FORCE_BUNDLING=1 detox build -c ios.sim.release
    script:
    - detox test -c ios.sim.release --no-color --headless --cleanup
